export const allItems = [
    { _id: "101", title: "All Categories" },
    { _id: "102", title: "Arts & Crafts" },
    { _id: "103", title: "Automotive" },
    { _id: "104", title: "Baby" },
    { _id: "105", title: "Beauty & Personal Care" },
    { _id: "106", title: "Books" },
    { _id: "107", title: "Boys' Fashion" },
    { _id: "108", title: "Computers" },
    { _id: "109", title: "Deals" },
    { _id: "110", title: "Digital Music" },
    { _id: "111", title: "Electronics" },
    { _id: "112", title: "Girls' Fashion" },
    { _id: "113", title: "Health & Household" },
    { _id: "114", title: "Home & Kitchen" },
    { _id: "115", title: "Industrial & Scientific" },
    { _id: "116", title: "Kindle Store" },
    { _id: "117", title: "Luggage" },
    { _id: "118", title: "Men's Fashion" },
    { _id: "119", title: "Movies & TV" },
    { _id: "120", title: "Music, CDs & Vinyl" },
    { _id: "121", title: "Pet Supplies" },
    { _id: "122", title: "Prime Video" },
    { _id: "123", title: "Software" },
    { _id: "124", title: "Sports & Outdoors" },
    { _id: "125", title: "Tools & Home Improvement" },
    { _id: "126", title: "Toys & Games" },
    { _id: "127", title: "Video Games" },
    { _id: "128", title: "Women's Fashion" },
];
export const footerBottomItem = [
    {
        _id: 1001,
        title: "AbeBooks",
        des:"Books, art & collectibles",
    },
    {
        _id: 1002,
        title: "Shopbop",
        des:"Designer Fashion Brands",
    },
    {
        _id: 1003,
        title: "Amazon Business",
        des:"Everything For Your Business",
    },
    {
        _id: 1004,
        title: "Prime Now",
        des:"2-Hour Delivery on Everyday Items",
    },
    {
        _id: 1005,
        title: "IMDb",
        des:"Movies, TV & Celebrities",
    },
    {
        _id: 1006,
        title: "Amazon Prime Music",
        des:"100 million songs, ad-free Over 15 million podcast episodes",
    },
    {
        _id: 1007,
        title: "Amazon Web Services",
        des:"Scalable Cloud Computing Services",
    },
    {
        _id: 1008,
        title: "Audible",
        des:"Download Audio Books",
    },
]